accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

jeerer_app/urls.py
from django.urls import path

from . import views

app_name = 'jeerer_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('board/', views.board_create, name='board_create'),
    path('board/<int:board_id>/', views.board, name='board'),
    path('board/<int:board_id>/card/', views.card_create, name='card_create'),
    path('board/<int:board_id>/card/<int:card_id>/', views.card, name='card'),
    path('board/<int:board_id>/card/<int:card_id>/delete/', views.card_delete, name='card_delete'),
    path('board/<int:board_id>/card/<int:card_id>/children/', views.children, name='children'),
    path('board/<int:board_id>/card/<int:card_id>/done/', views.mark_done, name='mark_done'),
]

jeerersite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('donzo/', include('jeerer_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

jeerer_app/models/board.py
from django.db import models
from django.contrib.auth.models import User


class BoardModel(models.Model):
    name = models.CharField(max_length=256)
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_all_cards(self):
        return list(self.cardmodel_set.all())

    def get_done_cards(self):
        done_cards = [card for card in self.cardmodel_set.all() if card.is_done()]
        # If Task A is made of subtask 1 and 2 then we don't care that 1 is done if A is done
        return list(filter(lambda card: card.parent not in done_cards, done_cards))

    def get_unfinished_cards(self):
        unfinished_cards = [card for card in self.cardmodel_set.all() if not card.is_done()]

        # We only want to see things that can be worked on (the smallest unfinished subtasks)
        return list(filter(lambda card: not card.get_children(), unfinished_cards))

jeerer_app/models/card.py
from django.db import models
from typing import Iterable
from .board import BoardModel


class CardModel(models.Model):
    board = models.ForeignKey(BoardModel, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=256)
    done = models.BooleanField(default=False)

    def __str__(self):
        family_history = []
        current_generation = self
        while current_generation is not None:
            family_history.insert(0, current_generation.name)
            current_generation = current_generation.parent

        return '~>'.join(family_history)

    def split(self, new_cards: Iterable[str]):
        for name in new_cards:
            CardModel.objects.create(board=self.board, name=name, parent=self)

    def get_children(self):
        return list(CardModel.objects.filter(parent=self))

    def get_all_children(self):
        all_children = []
        for child in self.get_children():
            all_children.append(child)
            all_children.extend(child.get_all_children())

        return all_children

    def get_parent(self):
        return self.parent

    def is_done(self) -> bool:
        children = self.get_children()
        if children:
            return all(map(lambda child: child.is_done(), children))

        return self.done

    def mark_done(self):
        self.done = True
        self.save()
        for child in self.get_children():
            child.mark_done()

jeerersite_project/jeerer_app/models.py
from __future__ import annotations
from django.db import models
from typing import Iterable


class CardModel(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=256)
    done = models.BooleanField(default=False)

    def __str__(self):
        family_history = []
        current_generation = self
        while current_generation is not None:
            family_history.insert(0, current_generation.name)
            current_generation = current_generation.parent

        return '~>'.join(family_history)

    def split(self, new_cards: List[str]):
        for name in new_cards:
            CardModel.objects.create(name=name, parent=self)

    def get_children(self) -> Iterable[CardModel]:
        return list(CardModel.objects.filter(parent=self))

    def get_all_children(self) -> Iterable[CardModel]:
        all_children = []
        for child in self.get_children():
            all_children.append(child)
            all_children.extend(child.get_all_children())

        return all_children

    def get_parent(self) -> CardModel:
        return self.parent

    def is_done(self) -> bool:
        children = self.get_children()
        if children:
            return all(map(lambda child: child.is_done(), children))

        return self.done

    def mark_done(self):
        self.done = True
        self.save()
        for child in self.get_children():
            child.mark_done()

jeerer_app/views.py
from django.http import HttpRequest, HttpResponseRedirect, HttpResponseForbidden
from .models import CardModel, BoardModel
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


def index(request: HttpRequest):
    all_boards = BoardModel.objects.all()

    context = {
        'board_list': filter(lambda board: request.user in board.users.all(), all_boards)
    }
    return render(request, 'jeerer_app/index.html', context)


def board_create(request: HttpRequest):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    new_board_name = request.POST['newBoard']
    if new_board_name != '':
        board = BoardModel.objects.create(name=new_board_name)
        board.users.add(request.user)
        return HttpResponseRedirect(reverse('jeerer_app:board', args=(board.id,)))
    return HttpResponseRedirect(reverse('jeerer_app:index'))


def board(request: HttpRequest, board_id: int):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    board = get_object_or_404(BoardModel, pk=board_id)

    if request.user not in board.users.all():
        return HttpResponseForbidden()

    context = {
        'board': board
    }
    return render(request, 'jeerer_app/board.html', context)


def card(request: HttpRequest, board_id: int, card_id: int):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    board = get_object_or_404(BoardModel, pk=board_id)

    if request.user not in board.users.all():
        return HttpResponseForbidden()

    card = get_object_or_404(CardModel, pk=card_id)

    if card.board != board:
        return HttpResponseForbidden()

    return render(request, 'jeerer_app/card.html', {'card': card})


def card_create(request: HttpRequest, board_id: int):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    board = get_object_or_404(BoardModel, pk=board_id)

    if request.user not in board.users.all():
        return HttpResponseForbidden()

    new_card_name = request.POST['newCard']
    if new_card_name != '':
        card = CardModel.objects.create(board=board, name=request.POST['newCard'])
        return HttpResponseRedirect(reverse('jeerer_app:card', args=(board_id, card.id,)))
    return render(request, 'jeerer_app/board.html', {'board': board})


def card_delete(request: HttpRequest, board_id: int, card_id: int):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    board = get_object_or_404(BoardModel, pk=board_id)

    if request.user not in board.users.all():
        return HttpResponseForbidden()

    card = get_object_or_404(CardModel, pk=card_id)

    if card.board != board:
        return HttpResponseForbidden()
    card.delete()
    return render(request, 'jeerer_app/board.html', {'board': board})


def mark_done(request: HttpRequest, board_id: int, card_id: int):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    board = get_object_or_404(BoardModel, pk=board_id)

    if request.user not in board.users.all():
        return HttpResponseForbidden()

    card = get_object_or_404(CardModel, pk=card_id)

    if card.board != board:
        return HttpResponseForbidden()
    card.mark_done()
    return HttpResponseRedirect(reverse('jeerer_app:board', args=(board_id,)))


def children(request: HttpRequest, board_id: int, card_id: int):
    parent = get_object_or_404(CardModel, pk=card_id)
    if request.method == 'POST':
        new_card_name = request.POST['newCard']
        if new_card_name != '':
            parent.split([new_card_name])
        return HttpResponseRedirect(reverse('jeerer_app:card', args=(board_id, card_id,)))

jeerer_app/templates/jeerer_app/board.html
<h1>To Do List</h1>
    <ul>
    {% for card in board.get_unfinished_cards %}
        <li><a href="{% url 'jeerer_app:card' board.id card.id %}">{{ card }}</a>: <a href="{% url 'jeerer_app:mark_done' board.id card.id %}">Mark Card as Done</a></li>
    {% endfor %}
    </ul>

<h1>Done List</h1>
    <ul>
    {% for card in board.get_done_cards %}
        <li><a href="{% url 'jeerer_app:card' board.id card.id %}">{{ card }}</a></li>
    {% endfor %}
    </ul>
<form action="{% url 'jeerer_app:card_create' board.id %}" method="post">
{% csrf_token %}
    <input type="text" name="newCard">
    <input type="submit" value="Create Card">
</form>
<br>
<a href="{% url 'jeerer_app:index' %}">Back to boards</a>

jeerer_app/templates/jeerer_app/card.html
<a href="{% url 'jeerer_app:board' card.board.id %}">Back to board</a>
<h1>{{ card }} {% if card.is_done %}
✓
{% else %}
X <a href="{% url 'jeerer_app:mark_done' card.board.id card.id %}">Mark Card as Done</a>
{% endif %}</h1>

{% if card.parent %}
<a href="{% url 'jeerer_app:card' card.board.id card.parent.id %}">Parent: {{ card.parent }}</a>
{% endif %}

<h3>Children</h3>
<ul>
{% for card in card.get_all_children %}
    <li><a href="{% url 'jeerer_app:card' card.board.id card.id %}">{{ card }}</a>
        {% if not card.is_done %}
             <a href="{% url 'jeerer_app:mark_done' card.board.id card.id %}">Mark Card as Done</a></li>
        {% endif %}
{% endfor %}
</ul>

<form action="{% url 'jeerer_app:children' card.board.id card.id %}" method="post">
{% csrf_token %}
    <input type="text" name="newCard" multiple>
    <input type="submit" value="Add Child">
</form>

<form action="{% url 'jeerer_app:card_delete' card.board.id card.id %}" method="post">
{% csrf_token %}
    <input type="submit" value="Delete Card">
</form>


<br>

jeerer_app/templates/jeerer_app/index.html
{% if board_list %}
    <ul>
    {% for board in board_list %}
        <li><a href="{% url 'jeerer_app:board' board.id %}">{{ board }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No boards.</p>
{% endif %}
<form action="{% url 'jeerer_app:board_create' %}" method="post">
{% csrf_token %}
    <input type="text" name="newBoard">
    <input type="submit" value="Create Board">
</form>
<a href="{% url 'home' %}">Back to home</a>