accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

jeerer_app/urls.py
from django.urls import path

from . import views

app_name = 'jeerer_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('board/', views.board_create, name='board_create'),
    path('board/<int:board_id>/', views.board, name='board'),
    path('board/<int:board_id>/card/', views.card_create, name='card_create'),
    path('board/<int:board_id>/card/<int:card_id>/', views.card, name='card'),
    path('board/<int:board_id>/card/<int:card_id>/delete/', views.card_delete, name='card_delete'),
    path('board/<int:board_id>/card/<int:card_id>/children/', views.children, name='children'),
    path('board/<int:board_id>/card/<int:card_id>/done/', views.mark_done, name='mark_done'),
]

jeerersite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('donzo/', include('jeerer_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Jeerer App{% endblock %}</title>
</head>
<body>
  <main>
    {% if user.is_authenticated %}
      {% block content %}
      {% endblock %}
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <a href="{% url 'jeerer_app:index' %}">Go to boards</a>
{% endblock %}